### ISSUE TITLE
DAG based on raw data

### ISSUE THREAD

**Issue by dinani65** [fishmoon1234/DAG-NoCurl#1]
Thanks for your sharing code.
I would appreciate it if you can answer my question.
can we use this code when the input is a set of observations of random variables? Based on the code, it seems to be necessary to have a weighted adjacency matrix.
Thanks in advance,

**Comment by fishmoon1234** [comment]
Yes you can. We use a weighted adjacency matrix just to check the accuracy (SHD) and it is not necessary for using the code. You can just modify line 118 and line 155 of "main_efficient.py", to load your data (variable X) without the ground truth weighted adjacency matrix (variable G). Or you can simply set G as all zeros in your dataset if you don't want to modify the code.
